//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBangTotNghiep_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class nv_DotCapBangTN
    {
        public int Id_Dot_Cap { get; set; }
        public string Ten_Van_Bang { get; set; }
        public string Ten_Dot_Cap { get; set; }
    }
}
