//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBangTotNghiep_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class nv_VanBangTN
    {
        public int Id_VanBang { get; set; }
        public string So_Hieu_Van_Bang { get; set; }
        public string Ma_SV { get; set; }
        public string Ho_Va_Ten { get; set; }
        public bool Gioi_Tinh { get; set; }
        public System.DateTime Ngay_Sinh { get; set; }
        public string Noi_Sinh { get; set; }
        public string Nganh_Hoc { get; set; }
        public string Khoa_Hoc { get; set; }
        public System.DateTime Ngay_Cap { get; set; }
        public string Xep_Loai_Tot_Nghiep { get; set; }
    }
}
